### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by danyeaw** [gaphor/generic#2]
https://github.com/gaphor/gaphor is using generic for events and multidispatch. When we upgraded to Python 3, we pulled the code from the library in as a sort of fork and updated it. It would be nice to clean things up and and push the changes upstream. Are you still accepting PRs? If so, would you like to keep Python 2 compatibility, or just drop it now that Python 2.7 is end of life?

**Comment by andreypopp** [comment]
I don’t intend to maintain this package going forward as I don’t use it long time already. I’d be happy to transfer the repo/package  to you or feel free to publish a fork.

**Comment by danyeaw** [comment]
@andreypopp Could you transfer the repo/PyPI/rtd to the Gaphor organization? We can take it over.

**Comment by andreypopp** [comment]
Transfering to you on gh and pypi, what your username on rtd?

**Comment by danyeaw** [comment]
dan@yeaw.me

**Comment by andreypopp** [comment]
it says such user does not exist, it probably wants a username not email

**Comment by danyeaw** [comment]
danyeaw is the username

**Comment by andreypopp** [comment]
done on all three

**Comment by danyeaw** [comment]
@andreypopp Thanks we'll try to take good care of it for you 😄

**Comment by amolenaar** [comment]
@andreypopp Thanks, Andrey!

**Comment by danyeaw** [comment]
Generic now supports Python 3.7 and 3.8 thanks to the awesome work by @amolenaar :tada:
