### ISSUE TITLE
Convert the print into logging so one can disable it

### ISSUE THREAD

**Issue by surister** [gaphor/generic#321]
**Is your feature request related to a problem? Please describe.**
Love the package, don't like the print statements, they clutter my output.

![image](https://user-images.githubusercontent.com/37985796/235865452-7c9ebb1c-7551-492c-83b1-49643fd35eba.png)

**Describe the solution you'd like**
Make it into logging.info so I one have finer control.

**Comment by danyeaw** [comment]
Hey @surister, thanks for the issue report. This is fixed by #323 and a new release is now out.
